// <auto-generated />
using System;
using AnydeskTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnydeskTracker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206085037_PcSchedulesLogs")]
    partial class PcSchedulesLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("AnydeskTracker.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastNotificationTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelegramUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AnydeskTracker.Models.BlockedAgentEmail", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("BlockedAgentEmails", (string)null);
                });

            modelBuilder.Entity("AnydeskTracker.Models.BlockedAgentPhone", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Phone");

                    b.ToTable("BlockedAgentPhones", (string)null);
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.BotGameAssignmentGlobal", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.ToTable("BotGameAssignmentsGlobal");
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.BotGameAssignmentOverride", b =>
                {
                    b.Property<int>("PcId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("PcId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("BotGameAssignmentsOverride");
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("GameCatalog");
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.GameSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameSchedules");
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.GameUserScheduleToUser", b =>
                {
                    b.Property<int>("GameUserScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("GameUserScheduleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("GameUserScheduleToUser");
                });

            modelBuilder.Entity("AnydeskTracker.Models.PcBotAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiskStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Error")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PcId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessesStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RamStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchedulerStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PcId");

                    b.ToTable("BotActions");
                });

            modelBuilder.Entity("AnydeskTracker.Models.PcBotDolphinAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PcId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PcId");

                    b.ToTable("DolphinActions");
                });

            modelBuilder.Entity("AnydeskTracker.Models.PcModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgentReady")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("AhkError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnyDeskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BotId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLaunchTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastStatusChange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextLaunchTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RustDeskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pcs");
                });

            modelBuilder.Entity("AnydeskTracker.Models.PcUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PauseStartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PcId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TotalPauseTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PcId");

                    b.HasIndex("WorkSessionId");

                    b.ToTable("PcUsages");
                });

            modelBuilder.Entity("AnydeskTracker.Models.UserAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkSessionId");

                    b.ToTable("UserActions");
                });

            modelBuilder.Entity("AnydeskTracker.Models.WorkSessionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PauseStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TotalPauseTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkSessionModels");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.BotGameAssignmentGlobal", b =>
                {
                    b.HasOne("AnydeskTracker.Models.Game.Game", "Game")
                        .WithOne("GlobalOrder")
                        .HasForeignKey("AnydeskTracker.Models.Game.BotGameAssignmentGlobal", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.BotGameAssignmentOverride", b =>
                {
                    b.HasOne("AnydeskTracker.Models.Game.Game", "Game")
                        .WithMany("PcOverrides")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnydeskTracker.Models.PcModel", "Pc")
                        .WithMany("OverridenBotGames")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.GameSchedule", b =>
                {
                    b.HasOne("AnydeskTracker.Models.Game.Game", "Game")
                        .WithMany("UserSchedules")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.GameUserScheduleToUser", b =>
                {
                    b.HasOne("AnydeskTracker.Models.Game.GameSchedule", "GameSchedule")
                        .WithMany("UserLinks")
                        .HasForeignKey("GameUserScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnydeskTracker.Models.AppUser", "User")
                        .WithMany("GameScheduleLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSchedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnydeskTracker.Models.PcBotAction", b =>
                {
                    b.HasOne("AnydeskTracker.Models.PcModel", "PcModel")
                        .WithMany()
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PcModel");
                });

            modelBuilder.Entity("AnydeskTracker.Models.PcBotDolphinAction", b =>
                {
                    b.HasOne("AnydeskTracker.Models.PcModel", "PcModel")
                        .WithMany()
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PcModel");
                });

            modelBuilder.Entity("AnydeskTracker.Models.PcModel", b =>
                {
                    b.OwnsOne("AnydeskTracker.Models.PcBotSchedule", "LastActiveSchedule", b1 =>
                        {
                            b1.Property<int>("PcModelId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeSpan?>("EndTod")
                                .HasColumnType("TEXT");

                            b1.Property<int>("IntervalMinutes")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeSpan>("StartTod")
                                .HasColumnType("TEXT");

                            b1.HasKey("PcModelId");

                            b1.ToTable("Pcs");

                            b1.WithOwner()
                                .HasForeignKey("PcModelId");
                        });

                    b.OwnsOne("AnydeskTracker.Models.PcBotSchedule", "PcBotSchedule", b1 =>
                        {
                            b1.Property<int>("PcModelId")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeSpan?>("EndTod")
                                .HasColumnType("TEXT");

                            b1.Property<int>("IntervalMinutes")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeSpan>("StartTod")
                                .HasColumnType("TEXT");

                            b1.HasKey("PcModelId");

                            b1.ToTable("Pcs");

                            b1.WithOwner()
                                .HasForeignKey("PcModelId");
                        });

                    b.Navigation("LastActiveSchedule");

                    b.Navigation("PcBotSchedule")
                        .IsRequired();
                });

            modelBuilder.Entity("AnydeskTracker.Models.PcUsage", b =>
                {
                    b.HasOne("AnydeskTracker.Models.PcModel", "Pc")
                        .WithMany()
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnydeskTracker.Models.WorkSessionModel", "WorkSession")
                        .WithMany("ComputerUsages")
                        .HasForeignKey("WorkSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pc");

                    b.Navigation("WorkSession");
                });

            modelBuilder.Entity("AnydeskTracker.Models.UserAction", b =>
                {
                    b.HasOne("AnydeskTracker.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnydeskTracker.Models.WorkSessionModel", "WorkSession")
                        .WithMany()
                        .HasForeignKey("WorkSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkSession");
                });

            modelBuilder.Entity("AnydeskTracker.Models.WorkSessionModel", b =>
                {
                    b.HasOne("AnydeskTracker.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AnydeskTracker.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AnydeskTracker.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnydeskTracker.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AnydeskTracker.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnydeskTracker.Models.AppUser", b =>
                {
                    b.Navigation("GameScheduleLinks");
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.Game", b =>
                {
                    b.Navigation("GlobalOrder");

                    b.Navigation("PcOverrides");

                    b.Navigation("UserSchedules");
                });

            modelBuilder.Entity("AnydeskTracker.Models.Game.GameSchedule", b =>
                {
                    b.Navigation("UserLinks");
                });

            modelBuilder.Entity("AnydeskTracker.Models.PcModel", b =>
                {
                    b.Navigation("OverridenBotGames");
                });

            modelBuilder.Entity("AnydeskTracker.Models.WorkSessionModel", b =>
                {
                    b.Navigation("ComputerUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
